In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://github.com/NadimKawwa/WomeneCommerce/raw/master/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df.describe()

Unnamed: 0   Clothing ID           Age        Rating  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean   11742.500000    918.118709     43.198544      4.196032   
std     6779.968547    203.298980     12.279544      1.110031   
min        0.000000      0.000000     18.000000      1.000000   
25%     5871.250000    861.000000     34.000000      4.000000   
50%    11742.500000    936.000000     41.000000      5.000000   
75%    17613.750000   1078.000000     52.000000      5.000000   
max    23485.000000   1205.000000     99.000000      5.000000   

       Recommended IND  Positive Feedback Count  
count     23486.000000             23486.000000  
mean          0.822362                 2.535936  
std           0.382216                 5.702202  
min           0.000000                 0.000000  
25%           1.000000                 0.000000  
50%           1.000000                 1.000000  
75%           1.000000                 3.000000  
max           1.000000               122.000000

In [6]:
df.shape

(23486, 11)

In [7]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [8]:
df[df['Review Text']==""]=np.NaN

In [9]:
df['Review Text'].fillna('No Review',inplace=True)

In [10]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [11]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [12]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [13]:
X = df['Review Text']

In [14]:
y = df['Rating']

In [15]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, random_state =2529)

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(lowercase = True,analyzer='word',ngram_range=(2,3), stop_words= 'english', max_features= 5000)

In [21]:
X_train = cv.fit_transform(X_train)

In [22]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [23]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
X_test = cv.fit_transform(X_test)

In [25]:
cv.get_feature_names_out()

array(['10 12', '10 12 took', '10 12 tops', ..., 'years old',
       'yesterday love', 'yoga pants'], dtype=object)

In [26]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model = MultinomialNB() 

In [30]:
model.fit(X_train,y_train)

MultinomialNB()

In [31]:
y_pred = model.predict(X_test)

In [32]:
y_pred.shape

(7046,)

In [33]:
y_pred

array([2., 3., 3., ..., 5., 4., 5.])

In [34]:
model.predict_proba(X_test)

array([[0.26692373, 0.35957477, 0.30830537, 0.04730174, 0.01789439],
       [0.09725869, 0.09370016, 0.48762968, 0.26285916, 0.05855232],
       [0.21322638, 0.0344866 , 0.6775651 , 0.01713515, 0.05758676],
       ...,
       [0.22922895, 0.0288237 , 0.07354507, 0.02725008, 0.6411522 ],
       [0.01591788, 0.00115913, 0.00471111, 0.76076036, 0.21745151],
       [0.06184667, 0.09982129, 0.01834076, 0.04535696, 0.77463432]])

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [36]:
print(confusion_matrix(y_test,y_pred))

[[  29   26   35   32  141]
 [  48   43   91   75  186]
 [  78   96  152  172  326]
 [ 125  129  212  301  742]
 [ 327  330  394  648 2308]]


In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.05      0.11      0.07       263
         2.0       0.07      0.10      0.08       443
         3.0       0.17      0.18      0.18       824
         4.0       0.25      0.20      0.22      1509
         5.0       0.62      0.58      0.60      4007

    accuracy                           0.40      7046
   macro avg       0.23      0.23      0.23      7046
weighted avg       0.43      0.40      0.42      7046



In [38]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [39]:
df.replace({'Rating':{1.0:0,2.0:0,3.0:0,4.0:1,5.0:1}},inplace = True)

In [40]:
df['Rating'].value_counts()

1.0    18208
0.0     5278
Name: Rating, dtype: int64

In [41]:
y = df['Rating']

In [42]:
x = df['Review Text']

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train, x_test,y_train,y_test = train_test_split(x,y, train_size = 0.7, random_state = 2529)

In [45]:
x_train.shape, x_test.shape, y_train.shape,y_train.shape

((16440,), (7046,), (16440,), (16440,))

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
cv = CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2,3),stop_words='english', max_features=5000)

In [48]:
x_train = cv.fit_transform(x_train)

In [49]:
x_test = cv.fit_transform(x_test)

In [50]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
model = MultinomialNB()

In [52]:
model.fit(x_train, y_train)

MultinomialNB()

In [53]:
y_pred = model.predict(x_test)

In [55]:
y_pred.shape

(7046,)

In [56]:
y_pred

array([0., 0., 0., ..., 1., 1., 1.])

In [57]:
from sklearn.metrics import confusion_matrix, classification_report

In [58]:
print(confusion_matrix(y_test,y_pred))

[[ 482 1048]
 [ 973 4543]]


In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.33      0.32      0.32      1530
         1.0       0.81      0.82      0.82      5516

    accuracy                           0.71      7046
   macro avg       0.57      0.57      0.57      7046
weighted avg       0.71      0.71      0.71      7046

