In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Wine.csv')

In [3]:
df.head()

class_label class_name  alcohol  malic_acid   ash  alcalinity_of_ash  \
0            1     Barolo    14.23        1.71  2.43               15.6   
1            1     Barolo    13.20        1.78  2.14               11.2   
2            1     Barolo    13.16        2.36  2.67               18.6   
3            1     Barolo    14.37        1.95  2.50               16.8   
4            1     Barolo    13.24        2.59  2.87               21.0   

   magnesium  total_phenols  flavanoids  nonflavanoid_phenols  \
0        127           2.80        3.06                  0.28   
1        100           2.65        2.76                  0.26   
2        101           2.80        3.24                  0.30   
3        113           3.85        3.49                  0.24   
4        118           2.80        2.69                  0.39   

   proanthocyanins  color_intensity   hue  od280  proline  
0             2.29             5.64  1.04   3.92     1065  
1             1.28             4.38  1.05   3.40     1050  
2             2.81             5.68  1.03   3.17     1185  
3             2.18             7.80  0.86   3.45     1480  
4             1.82             4.32  1.04   2.93      735

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   class_label           178 non-null    int64  
 1   class_name            178 non-null    object 
 2   alcohol               178 non-null    float64
 3   malic_acid            178 non-null    float64
 4   ash                   178 non-null    float64
 5   alcalinity_of_ash     178 non-null    float64
 6   magnesium             178 non-null    int64  
 7   total_phenols         178 non-null    float64
 8   flavanoids            178 non-null    float64
 9   nonflavanoid_phenols  178 non-null    float64
 10  proanthocyanins       178 non-null    float64
 11  color_intensity       178 non-null    float64
 12  hue                   178 non-null    float64
 13  od280                 178 non-null    float64
 14  proline               178 non-null    int64  
dtypes: float64(11), int64(3

In [5]:
df.describe()

class_label     alcohol  malic_acid         ash  alcalinity_of_ash  \
count   178.000000  178.000000  178.000000  178.000000         178.000000   
mean      1.938202   13.000618    2.336348    2.366517          19.494944   
std       0.775035    0.811827    1.117146    0.274344           3.339564   
min       1.000000   11.030000    0.740000    1.360000          10.600000   
25%       1.000000   12.362500    1.602500    2.210000          17.200000   
50%       2.000000   13.050000    1.865000    2.360000          19.500000   
75%       3.000000   13.677500    3.082500    2.557500          21.500000   
max       3.000000   14.830000    5.800000    3.230000          30.000000   

        magnesium  total_phenols  flavanoids  nonflavanoid_phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       proanthocyanins  color_intensity         hue       od280      proline  
count       178.000000       178.000000  178.000000  178.000000   178.000000  
mean          1.590899         5.058090    0.957449    2.611685   746.893258  
std           0.572359         2.318286    0.228572    0.709990   314.907474  
min           0.410000         1.280000    0.480000    1.270000   278.000000  
25%           1.250000         3.220000    0.782500    1.937500   500.500000  
50%           1.555000         4.690000    0.965000    2.780000   673.500000  
75%           1.950000         6.200000    1.120000    3.170000   985.000000  
max           3.580000        13.000000    1.710000    4.000000  1680.000000

In [6]:
df.shape

(178, 15)

In [7]:
df.columns

Index(['class_label', 'class_name', 'alcohol', 'malic_acid', 'ash',
       'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids',
       'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue',
       'od280', 'proline'],
      dtype='object')

In [8]:
df['alcohol'].value_counts()

13.05    6
12.37    6
12.08    5
12.29    4
12.42    3
        ..
13.72    1
13.29    1
13.74    1
13.77    1
14.13    1
Name: alcohol, Length: 126, dtype: int64

In [9]:
df.groupby('alcohol').mean()

class_label  malic_acid   ash  alcalinity_of_ash  magnesium  \
alcohol                                                                
11.03            2.0        1.51  2.20               21.5       85.0   
11.41            2.0        0.74  2.50               21.0       88.0   
11.45            2.0        2.40  2.42               20.0       96.0   
11.46            2.0        3.74  1.82               19.5      107.0   
11.56            2.0        2.05  3.23               28.5      119.0   
...              ...         ...   ...                ...        ...   
14.37            1.0        1.95  2.50               16.8      113.0   
14.38            1.0        2.73  2.33               14.0      102.0   
14.39            1.0        1.87  2.45               14.6       96.0   
14.75            1.0        1.73  2.39               11.4       91.0   
14.83            1.0        1.64  2.17               14.0       97.0   

         total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
alcohol                                                                     
11.03            2.460       2.170                  0.52            2.010   
11.41            2.480       2.010                  0.42            1.440   
11.45            2.900       2.790                  0.32            1.830   
11.46            3.180       2.580                  0.24            3.580   
11.56            3.180       5.080                  0.47            1.870   
...                ...         ...                   ...              ...   
14.37            3.850       3.490                  0.24            2.180   
14.38            3.275       3.405                  0.28            2.575   
14.39            2.500       2.520                  0.30            1.980   
14.75            3.100       3.690                  0.43            2.810   
14.83            2.800       2.980                  0.29            1.980   

         color_intensity   hue  od280  proline  
alcohol                                         
11.03               1.90  1.71   2.87    407.0  
11.41               3.08  1.10   2.31    434.0  
11.45               3.25  0.80   3.39    625.0  
11.46               2.90  0.75   2.81    562.0  
11.56               6.00  0.93   3.69    465.0  
...                  ...   ...    ...      ...  
14.37               7.80  0.86   3.45   1480.0  
14.38               6.20  1.12   3.22   1306.0  
14.39               5.25  1.02   3.58   1290.0  
14.75               5.40  1.25   2.73   1150.0  
14.83               5.20  1.08   2.85   1045.0  

[126 rows x 13 columns]

In [11]:
y = df[['alcohol','class_label']]

In [12]:
y.shape

(178, 2)

In [13]:
y

alcohol  class_label
0      14.23            1
1      13.20            1
2      13.16            1
3      14.37            1
4      13.24            1
..       ...          ...
173    13.71            3
174    13.40            3
175    13.27            3
176    13.17            3
177    14.13            3

[178 rows x 2 columns]

In [14]:
x = df.drop(['alcohol','class_name','class_label'],axis=1)

In [15]:
x.shape

(178, 12)

In [16]:
x

malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0          1.71  2.43               15.6        127           2.80   
1          1.78  2.14               11.2        100           2.65   
2          2.36  2.67               18.6        101           2.80   
3          1.95  2.50               16.8        113           3.85   
4          2.59  2.87               21.0        118           2.80   
..          ...   ...                ...        ...            ...   
173        5.65  2.45               20.5         95           1.68   
174        3.91  2.48               23.0        102           1.80   
175        4.28  2.26               20.0        120           1.59   
176        2.59  2.37               20.0        120           1.65   
177        4.10  2.74               24.5         96           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280  proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 12 columns]

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc = StandardScaler()

In [19]:
x = sc.fit_transform(x)

In [20]:
x

array([[-0.5622498 ,  0.23205254, -1.16959318, ...,  0.36217728,
         1.84791957,  1.01300893],
       [-0.49941338, -0.82799632, -2.49084714, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.02123125,  1.10933436, -0.2687382 , ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 1.74474449, -0.38935541,  0.15166079, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.22769377,  0.01273209,  0.15166079, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.58316512,  1.36520822,  1.50294326, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [21]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test, y_train,y_test = train_test_split(x,y.iloc[:,1], test_size = 0.3, stratify= y.iloc[:,1],random_state=2529)

In [27]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((124, 12), (54, 12), (124,), (54,))

In [28]:
from sklearn.svm import SVC

In [29]:
svc = SVC()

In [30]:
svc.fit(x_train,y_train)

SVC()

In [31]:
y_pred = svc.predict(x_test)

In [32]:
y_pred.shape

(54,)

In [33]:
y_pred

array([2, 2, 2, 2, 2, 1, 3, 1, 2, 3, 1, 1, 1, 3, 1, 2, 2, 2, 3, 2, 3, 2,
       3, 2, 2, 1, 3, 3, 3, 2, 1, 3, 1, 1, 3, 1, 2, 3, 1, 3, 3, 1, 2, 1,
       1, 1, 1, 3, 2, 2, 2, 1, 2, 2])

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
print(confusion_matrix(y_test,y_pred))

[[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]


In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        21
           3       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [45]:
y = df['alcohol'].apply(lambda y_value: 1 if y_value>=6 else 0)

In [46]:
y.value_counts()

1    178
Name: alcohol, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3,random_state=2529) 

In [52]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((124, 12), (54, 12), (124,), (54,))

In [54]:
from sklearn.svm import SVC

In [55]:
svc = SVC()